// <auto-generated />
namespace BaiTapOnTap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class abcd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abcd));
        
        string IMigrationMetadata.Id
        {
            get { return "201912030904381_abcd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
